name: NetworkPluginApp
options:
  bundleIdPrefix: com.example
packages:
  AppExaminer:
    path: ../../
  AppExaminerNetworkPlugin:
    path: ../../
  FlipperDesktopAppConnection:
    path: ../../
  AppExaminerWebSocketServerConnection:
    path: ../../
targets:
  NetworkPluginApp:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: Sources
    dependencies:
      - package: AppExaminer
      - package: AppExaminerNetworkPlugin
      - package: FlipperDesktopAppConnection
      - package: AppExaminerWebSocketServerConnection
    info:
      path: Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: none
        NSLocalNetworkUsageDescription: "NSLocalNetworkUsageDescription"
