name: ExamplePluginApp
options:
  bundleIdPrefix: com.example
packages:
  AppExaminer:
    path: ../../
targets:
  ExamplePluginApp:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: Sources
    dependencies:
      - package: AppExaminer
    info:
      path: Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: none
